export const API_ENDPOINTS_B2B = {
  SEARCH: '/search/search',
  FILTER: '/search/facet',
  PRODCUTS: '/search/search',
  ERP_PRICES: '/erp/get_multiple_prices',
  GET_ORDERS: '/account/get_orders',
  GET_ORDER_DETAIL: '/wrapper/get_order_detail',
  GET_INVOICES: '/account/get_invoices',
  GET_DDT: '/account/get_ddt',
  GET_INVOICE_PDF: '/wrapper/invoice_pdf',
  GET_BARCODE_PDF: '/wrapper/pdf_barcode_document',
  GET_INVOICE_CSV: '/account/csv_invoice_document',
  GET_EXPOSITION: '/account/exposition',
  GET_PAYMENT_DEADLINE: '/account/payment_deadline',
  GET_ADDRESSES: '/account/get_addresses',
  GET_CUSTOMER: '/account/get_customer',
  RESET_PASSWORD: '/wrapper/reset_password',
  LOGIN: '/wrapper/login',
  PUSH: {
    VAPID_PUBLIC_KEY: '/push/vapid-public-key',
    SUBSCRIBE: '/push/subscribe',
    UNSUBSCRIBE: '/push/unsubscribe',
    PREFERENCES: '/push/preferences',
    TRACK_CLICK: (pushId: string) => `/push/track/click/${pushId}`,
  },
};
