# syntax=docker/dockerfile:1.6

ARG NODE_IMAGE=node:20-alpine
ARG PNPM_VERSION=9.5.0

# Base image with pnpm enabled
FROM ${NODE_IMAGE} AS base
WORKDIR /app
ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate

# Install dependencies (cached by lockfile)
FROM base AS deps
COPY package.json pnpm-lock.yaml ./
# Use BuildKit cache for the pnpm store for faster repeated builds
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

# Build the app
FROM base AS build
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
# Accept build-time args and expose them as env for Next build

# Multi-Tenant Mode Configuration (build-time)
ARG TENANT_MODE=single
ARG POOL_MAX_CONNECTIONS=50
ARG POOL_PER_DB_SIZE=10
ARG POOL_TTL_MS=1800000
ARG TENANT_CACHE_TTL_SECONDS=300

# Single-Tenant Configuration (used when TENANT_MODE=single)
ARG NEXT_PUBLIC_TENANT_ID
ARG NEXT_PUBLIC_PROJECT_CODE
ARG NEXT_PROJECT_CODE
ARG NEXT_PUBLIC_API_KEY_ID
ARG NEXT_PUBLIC_API_SECRET
ARG API_KEY_ID
ARG API_SECRET

# API URLs
ARG NEXT_PUBLIC_REST_API_ENDPOINT
ARG NEXT_PUBLIC_B2B_PUBLIC_REST_API_ENDPOINT
ARG NEXT_PUBLIC_WEBSITE_URL
ARG NEXT_PUBLIC_GOOGLE_API_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLIC_KEY
ARG CMS_PUBLIC_REST_API_ENDPOINT
ARG NEXT_PUBLIC_B2B_BUILDER_URL
ARG VINC_STOREFRONT_URL
ARG NEXT_PUBLIC_PIM_API_URL
ARG PIM_API_PRIVATE_URL
ARG VINC_API_URL
ARG VINC_INTERNAL_API_KEY

# Multi-Tenant Mode Configuration
ENV TENANT_MODE=$TENANT_MODE
ENV POOL_MAX_CONNECTIONS=$POOL_MAX_CONNECTIONS
ENV POOL_PER_DB_SIZE=$POOL_PER_DB_SIZE
ENV POOL_TTL_MS=$POOL_TTL_MS
ENV TENANT_CACHE_TTL_SECONDS=$TENANT_CACHE_TTL_SECONDS

# Single-Tenant Configuration
ENV NEXT_PUBLIC_TENANT_ID=$NEXT_PUBLIC_TENANT_ID
ENV NEXT_PUBLIC_PROJECT_CODE=$NEXT_PUBLIC_PROJECT_CODE
ENV NEXT_PROJECT_CODE=$NEXT_PROJECT_CODE
ENV NEXT_PUBLIC_API_KEY_ID=$NEXT_PUBLIC_API_KEY_ID
ENV NEXT_PUBLIC_API_SECRET=$NEXT_PUBLIC_API_SECRET
ENV API_KEY_ID=$API_KEY_ID
ENV API_SECRET=$API_SECRET

# API URLs
ENV NEXT_PUBLIC_REST_API_ENDPOINT=$NEXT_PUBLIC_REST_API_ENDPOINT
ENV NEXT_PUBLIC_B2B_PUBLIC_REST_API_ENDPOINT=$NEXT_PUBLIC_B2B_PUBLIC_REST_API_ENDPOINT
ENV NEXT_PUBLIC_WEBSITE_URL=$NEXT_PUBLIC_WEBSITE_URL
ENV NEXT_PUBLIC_GOOGLE_API_KEY=$NEXT_PUBLIC_GOOGLE_API_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLIC_KEY=$NEXT_PUBLIC_STRIPE_PUBLIC_KEY
ENV CMS_PUBLIC_REST_API_ENDPOINT=$CMS_PUBLIC_REST_API_ENDPOINT
ENV NEXT_PUBLIC_B2B_BUILDER_URL=$NEXT_PUBLIC_B2B_BUILDER_URL
ENV VINC_STOREFRONT_URL=$VINC_STOREFRONT_URL
ENV NEXT_PUBLIC_PIM_API_URL=$NEXT_PUBLIC_PIM_API_URL
ENV PIM_API_PRIVATE_URL=$PIM_API_PRIVATE_URL
ENV VINC_API_URL=$VINC_API_URL
ENV VINC_INTERNAL_API_KEY=$VINC_INTERNAL_API_KEY

RUN --mount=type=cache,id=next-cache,target=/app/.next/cache pnpm build

# Production runtime using Next.js standalone output
FROM ${NODE_IMAGE} AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Re-declare args and set runtime envs for SSR/server usage

# Multi-Tenant Mode Configuration (build-time defaults)
ARG TENANT_MODE=single
ARG POOL_MAX_CONNECTIONS=50
ARG POOL_PER_DB_SIZE=10
ARG POOL_TTL_MS=1800000
ARG TENANT_CACHE_TTL_SECONDS=300

# Single-Tenant Configuration (used when TENANT_MODE=single)
ARG NEXT_PUBLIC_TENANT_ID
ARG NEXT_PUBLIC_PROJECT_CODE
ARG NEXT_PROJECT_CODE
ARG NEXT_PUBLIC_API_KEY_ID
ARG NEXT_PUBLIC_API_SECRET
ARG API_KEY_ID
ARG API_SECRET

# API URLs
ARG NEXT_PUBLIC_REST_API_ENDPOINT
ARG NEXT_PUBLIC_B2B_PUBLIC_REST_API_ENDPOINT
ARG NEXT_PUBLIC_WEBSITE_URL
ARG NEXT_PUBLIC_GOOGLE_API_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLIC_KEY
ARG CMS_PUBLIC_REST_API_ENDPOINT
ARG NEXT_PUBLIC_B2B_BUILDER_URL
ARG VINC_STOREFRONT_URL
ARG NEXT_PUBLIC_PIM_API_URL
ARG PIM_API_PRIVATE_URL
ARG VINC_API_URL
ARG VINC_INTERNAL_API_KEY

# Multi-Tenant Mode Configuration
# MONGO_URL and MONGO_DB are provided by cluster at runtime
ENV TENANT_MODE=$TENANT_MODE
ENV POOL_MAX_CONNECTIONS=$POOL_MAX_CONNECTIONS
ENV POOL_PER_DB_SIZE=$POOL_PER_DB_SIZE
ENV POOL_TTL_MS=$POOL_TTL_MS
ENV TENANT_CACHE_TTL_SECONDS=$TENANT_CACHE_TTL_SECONDS

# Single-Tenant Configuration
ENV NEXT_PUBLIC_TENANT_ID=$NEXT_PUBLIC_TENANT_ID
ENV NEXT_PUBLIC_PROJECT_CODE=$NEXT_PUBLIC_PROJECT_CODE
ENV NEXT_PROJECT_CODE=$NEXT_PROJECT_CODE
ENV NEXT_PUBLIC_API_KEY_ID=$NEXT_PUBLIC_API_KEY_ID
ENV NEXT_PUBLIC_API_SECRET=$NEXT_PUBLIC_API_SECRET
ENV API_KEY_ID=$API_KEY_ID
ENV API_SECRET=$API_SECRET

# API URLs
ENV NEXT_PUBLIC_REST_API_ENDPOINT=$NEXT_PUBLIC_REST_API_ENDPOINT
ENV NEXT_PUBLIC_B2B_PUBLIC_REST_API_ENDPOINT=$NEXT_PUBLIC_B2B_PUBLIC_REST_API_ENDPOINT
ENV NEXT_PUBLIC_WEBSITE_URL=$NEXT_PUBLIC_WEBSITE_URL
ENV NEXT_PUBLIC_GOOGLE_API_KEY=$NEXT_PUBLIC_GOOGLE_API_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLIC_KEY=$NEXT_PUBLIC_STRIPE_PUBLIC_KEY
ENV CMS_PUBLIC_REST_API_ENDPOINT=$CMS_PUBLIC_REST_API_ENDPOINT
ENV NEXT_PUBLIC_B2B_BUILDER_URL=$NEXT_PUBLIC_B2B_BUILDER_URL
ENV VINC_STOREFRONT_URL=$VINC_STOREFRONT_URL
ENV NEXT_PUBLIC_PIM_API_URL=$NEXT_PUBLIC_PIM_API_URL
ENV PIM_API_PRIVATE_URL=$PIM_API_PRIVATE_URL
ENV VINC_API_URL=$VINC_API_URL
ENV VINC_INTERNAL_API_KEY=$VINC_INTERNAL_API_KEY

# Run as non-root user for security
RUN addgroup -S nextjs && adduser -S nextjs -G nextjs

# Remove wget/curl/shell utilities to prevent RCE exploitation
RUN rm -f /usr/bin/wget /usr/bin/curl 2>/dev/null || true

# Create cache directory with correct permissions BEFORE switching user
RUN mkdir -p /app/.next/cache && chown -R nextjs:nextjs /app/.next

# Copy standalone server and static assets (as root, then fix ownership)
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public

# Fix ownership of all copied files
RUN chown -R nextjs:nextjs /app

# Switch to non-root user
USER nextjs

EXPOSE 3000
CMD ["node", "server.js"]
